---
- hosts: all
  tasks:
    - name: create DB
      shell: |
        MYSQL_ROOT_PASSWORD={{ password }}
        SECURE_MYSQL=$(expect -c "
        set timeout 10
        spawn mysql 
        expect \">\"
        send \"CREATE DATABASE glance;\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'localhost' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON glance.* TO 'glance'@'%' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        send \"exit\r\"
        ")
        echo "$SECURE_MYSQL"
    - name: creating glance environoment
      shell: |
        source ~/openrc.sh
        openstack user create --domain default --password {{ password }} glance
        openstack role add --project admin --user glance admin
        openstack service create --name glance --description "OpenStack Image" image
        openstack endpoint create --region RegionOne image public http://{{ myname }}:9292
        openstack endpoint create --region RegionOne image internal http://{{ myname }}:9292
        openstack endpoint create --region RegionOne image admin http://{{ myname }}:9292
    - name: Install glance
      yum: name=openstack-glance state=latest
    - name: settingup glance
      shell: |
        openstack-config --set /etc/glance/glance-api.conf DEFAULT notification_driver noop
        openstack-config --set /etc/glance/glance-api.conf database connection mysql+pymysql://glance:{{ password }}@{{ myname }}/glance
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_uri http://{{ myname }}:5000
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_url http://{{ myname }}:35357
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken memcached_servers {{ myname }}:11211
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken auth_type password
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken project_domain_name default
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken user_domain_name default
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken project_name admin
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken username glance
        openstack-config --set /etc/glance/glance-api.conf keystone_authtoken password {{ password }}
        openstack-config --set /etc/glance/glance-api.conf paste_deploy flavor keystone
        openstack-config --set /etc/glance/glance-api.conf glance_store stores file,http
        openstack-config --set /etc/glance/glance-api.conf glance_store default_store file
        openstack-config --set /etc/glance/glance-api.conf glance_store filesystem_store_datadir /var/lib/glance/images/
        openstack-config --set /etc/glance/glance-registry.conf database connection mysql+pymysql://glance:{{ password }}@{{ myname }}/glance
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_uri http://{{ myname }}:5000
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_url http://{{ myname }}:35357
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken memcached_servers {{ myname }}:11211
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken auth_type {{ password }}
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken project_domain_name default
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken user_domain_name default
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken project_name admin
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken username glance
        openstack-config --set /etc/glance/glance-registry.conf keystone_authtoken password {{ password }}
        openstack-config --set /etc/glance/glance-registry.conf paste_deploy flavor keystone
        openstack-config --set /etc/glance/glance-registry.conf DEFAULT 
        su -s /bin/sh -c "glance-manage db_sync" glance
        systemctl enable openstack-glance-api.service openstack-glance-registry.service
        systemctl start openstack-glance-api.service openstack-glance-registry.service
