---
- hosts: all
  tasks:
    - name: create DB
      shell: |
        MYSQL_ROOT_PASSWORD={{ password }}
        SECURE_MYSQL=$(expect -c "
        set timeout 10
        spawn mysql 
        expect \">\"
        send \"CREATE DATABASE keystone;\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'localhost' IDENTIFIED BY '{{ password }}';\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON keystone.* TO 'keystone'@'%' IDENTIFIED BY '{{ password }}';\r\"
        expect \">\"
        send \"exit\r\"
        ")
        echo "$SECURE_MYSQL"
    - name: Install keystone and support files
      yum: state=present name={{ item }}
      with_items:
      - openstack-keystone
      - httpd 
      - mod_wsgi
      - python-openstackclient
    - name: config httpd
      shell: |
        cat >> /etc/httpd/conf/httpd.conf <<EOF
        ServerName {{ myfqdn }}
    - name: setting up keystone
      shell: |
        openstack-config --set /etc/keystone/keystone.conf database connection mysql+pymysql://keystone:{{ password }}@{{ myname }}/keystone
        openstack-config --set /etc/keystone/keystone.conf token provider fernet
        su -s /bin/sh -c "keystone-manage db_sync" keystone
        keystone-manage fernet_setup --keystone-user keystone --keystone-group keystone
        keystone-manage credential_setup --keystone-user keystone --keystone-group keystone
        keystone-manage bootstrap --bootstrap-password {{ password}} --bootstrap-admin-url http://{{ myname }}:35357/v3/ --bootstrap-internal-url http://{{ myname }}:35357/v3/ --bootstrap-public-url http://{{ myname }}:5000/v3/ --bootstrap-region-id RegionOne
        ln -s /usr/share/keystone/wsgi-keystone.conf /etc/httpd/conf.d/
        systemctl enable httpd.service
        systemctl start httpd.service
    - name: creating environoment
      shell: |
        cat >> ~/openstack-admin.rc <<EOF
        export OS_USERNAME=admin
        export OS_PASSWORD={{ password }}
        export OS_PROJECT_NAME=admin
        export OS_USER_DOMAIN_NAME=default
        export OS_PROJECT_DOMAIN_NAME=default
        export OS_AUTH_URL=http://{{ myname }}:35357/v3
        export OS_IDENTITY_API_VERSION=3
