---
- hosts: all
  tasks:
    - name: create DB
      shell: |
        MYSQL_ROOT_PASSWORD={{ password }}
        SECURE_MYSQL=$(expect -c "
        set timeout 10
        spawn mysql 
        expect \">\"
        send \"CREATE DATABASE neutron;\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'localhost' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON neutron.* TO 'neutron'@'%' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        ")
        echo "$SECURE_MYSQL"
    - name: creating neutron environoment
      shell: |
        source ~/openrc.sh
        openstack user create --domain default neutron --password {{ password }} --email neutron@nico.com
        openstack role add --project admin --user neutron admin
        openstack service create --name neutron --description "OpenStack Networking Service" network
        openstack endpoint create --region RegionOne network public http://{{ myname }}:9696 
        openstack endpoint create --region RegionOne network internal http://{{ myname }}:9696 
        openstack endpoint create --region RegionOne network admin http://{{ myname }}:9696
    - name: install neutron and services
      yum: state=present name={{ item }}
      with_items:
      - openstack-neutron 
      - openstack-neutron-ml2 
      - openstack-neutron-openvswitch 
    - name: config network
      shell: |
        cat >> /etc/sysctl.conf <<EOF
        net.ipv4.ip_forward=1
        net.ipv4.conf.all.rp_filter=0
        net.ipv4.conf.default.rp_filter=0
    - name: activating changes
      shell: sysctl -p
    - name: configure neutron services
      shell: |
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_uri http://{{ myname }}:5000
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_url http://{{ myname }}:35357
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken memcahed_servers {{ myname }}:11211
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken auth_type password
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken project_domain_name default
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken user_domain_name default
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken project_name admin
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken username neutron
        openstack-config --set /etc/neutron/neutron.conf keystone_authtoken password {{ password }}
        openstack-config --set /etc/neutron/neutron.conf DEFAULT auth_strategy keystone
        openstack-config --set /etc/neutron/neutron.conf DEFAULT state_path /var/lib/neutron
        openstack-config --set /etc/neutron/neutron.conf DEFAULT dhcp_agent_notification True
        openstack-config --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_status_changes True
        openstack-config --set /etc/neutron/neutron.conf DEFAULT notify_nova_on_port_data_changes True
        openstack-config --set /etc/neutron/neutron.conf DEFAULT interface_driver neutron.agent.linux.interface.OVSInterfaceDriver
        openstack-config --set /etc/neutron/neutron.conf DEFAULT transport_url rabbit://openstack:{{ password }}@{{ myname }}
        openstack-config --set /etc/neutron/neutron.conf database connection mysql+pymysql://neutron:{{ password }}@{{ myname }}/neutron
        openstack-config --set /etc/neutron/neutron.conf DEFAULT core_plugin ml2
        openstack-config --set /etc/neutron/neutron.conf DEFAULT service_plugins router
        openstack-config --set /etc/neutron/neutron.conf DEFAULT allow_overlapping_ips True
        openstack-config --set /etc/neutron/neutron.conf nova auth_url http://{{ myname }}:35357
        openstack-config --set /etc/neutron/neutron.conf nova auth_type password
        openstack-config --set /etc/neutron/neutron.conf nova project_domain_name default
        openstack-config --set /etc/neutron/neutron.conf nova user_domain_name default
        openstack-config --set /etc/neutron/neutron.conf nova region_name RegionOne
        openstack-config --set /etc/neutron/neutron.conf nova project_name admin
        openstack-config --set /etc/neutron/neutron.conf nova username nova
        openstack-config --set /etc/neutron/neutron.conf nova password {{ password }}
        chmod 640 /etc/neutron/neutron.conf
        chgrp neutron /etc/neutron/neutron.conf
        openstack-config --set /etc/neutron/dhcp_agent.ini DEFAULT interface_driver neutron.agent.linux.interface.OVSInterfaceDriver
        openstack-config --set /etc/neutron/dhcp_agent.ini DEFAULT dhcp_driver neutron.agent.linux.dhcp.Dnsmasq
        openstack-config --set /etc/neutron/dhcp_agent.ini DEFAULT enable_isolated_metadata True
        openstack-config --set /etc/neutron/l3_agent.ini DEFAULT interface_driver neutron.agent.linux.interface.OVSInterfaceDriver
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 type_drivers flat,vlan,gre,vxlan
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 mechanism_drivers openvswitch,l2population
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 extension_drivers port_security
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 enable_ipset True
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 enable_security_group true 
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_flat flat_networks  *
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 firewall_driver neutron.agent.linux.iptables_firewall.OVSHybridIptablesFirewallDriver
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2 tenant_network_types gre
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ml2_type_gre tunnel_id_ranges 1:1000
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs local_ip {{ myip }}
        openstack-config --set /etc/neutron/plugins/ml2/ml2_conf.ini ovs bridge_mappings external:br-ex
        openstack-config --set  /etc/neutron/plugins/ml2/openvswitch_agent.ini ovs bridge_mappings external:br-ex
        openstack-config --set /etc/neutron/plugins/ml2/openvswitch_agent.ini agent tunnel_types gre
        openstack-config --set /etc/neutron/metadata_agent.ini DEFAULT nova_metadata_ip {{ myname }}
        openstack-config --set /etc/neutron/metadata_agent.ini DEFAULT nova_metadata_port 8775
        openstack-config --set /etc/neutron/metadata_agent.ini DEFAULT metadata_proxy_shared_secret {{ password }}
        openstack-config --set /etc/neutron/neutron.conf oslo_concurrency lock_path /var/lib/neutron/tmp
        openstack-config --set /etc/nova/nova.conf DEFAULT use_neutron True
        openstack-config --set /etc/nova/nova.conf DEFAULT linuxnet_interface_driver nova.network.linux_net.LinuxOVSInterfaceDriver
        openstack-config --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver
        openstack-config --set /etc/nova/nova.conf neutron url http://{{ myname }}:9696
        openstack-config --set /etc/nova/nova.conf neutron auth_url http://{{ myname }}:35357
        openstack-config --set /etc/nova/nova.conf neutron auth_type password
        openstack-config --set /etc/nova/nova.conf neutron project_domain_name default
        openstack-config --set /etc/nova/nova.conf neutron user_domain_name default
        openstack-config --set /etc/nova/nova.conf neutron region_name RegionOne
        openstack-config --set /etc/nova/nova.conf neutron project_name admin
        openstack-config --set /etc/nova/nova.conf neutron username neutron
        openstack-config --set /etc/nova/nova.conf neutron password {{ password }}
        openstack-config --set /etc/nova/nova.conf neutron service_metadata_proxy True
        openstack-config --set /etc/nova/nova.conf neutron metadata_proxy_shared_secret {{ password}}
        ln -s /etc/neutron/plugins/ml2/ml2_conf.ini /etc/neutron/plugin.ini
        su -s /bin/sh -c "neutron-db-manage --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head" neutron
        sed -i 's,plugins/openvswitch/ovs_neutron_plugin.ini,plugin.ini,g' /usr/lib/systemd/system/neutron-openvswitch-agent.service
        systemctl enable openvswitch.service
        systemctl start openvswitch.service
    - name: config br-ex
      shell:  |
        cat > /etc/sysconfig/network-scripts/ifcfg-br-ex <<EOF
        DEVICE=br-ex
        BOOTPROTO=static
        ONBOOT=yes
        IPADDR={{ exnetip1 }}
        PREFIX=24
        MTU=1400
        TYPE=OVSBridge
        OVS_Bridge=br-ex
        DEVICETYPE=ovs
    - name: config external interface {{ exint }}
      shell: |
        cat > /etc/sysconfig/network-scripts/ifcfg-{{ exint }} <<EOF
        DEVICE={{ exint }}
        ONBOOT=yes
        MTU=1400
        TYPE=OVSPort
        DEVICETYPE=ovs
        OVS_BRIDGE=br-ex
    - name: restart network
      shell: |
        ifdown br-ex
        ifup br-ex
        ifdown {{ exint  }}
        ifup {{ exint  }}
        systemctl restart openstack-nova-compute.service openstack-nova-api.service openstack-nova-scheduler.service openstack-nova-conductor.service
        systemctl enable openvswitch.service neutron-openvswitch-agent.service neutron-l3-agent.service neutron-dhcp-agent.service neutron-metadata-agent.service neutron-server.service
        systemctl start openvswitch.service neutron-openvswitch-agent.service neutron-l3-agent.service neutron-dhcp-agent.service neutron-metadata-agent.service neutron-server.service
        openstack-config --set /usr/lib/systemd/system/neutron-openvswitch-agent.service Service ExecStart "/usr/bin/neutron-openvswitch-agent --config-file /usr/share/neutron/neutron-dist.conf --config-file /etc/neutron/neutron.conf  --config-file /etc/neutron/plugins/ml2/openvswitch_agent.ini --config-file /etc/neutron/plugins/ml2/ml2_conf.ini --config-dir /etc/neutron/conf.d/common --config-dir /etc/neutron/conf.d/neutron-openvswitch-agent --log-file /var/log/neutron/openvswitch-agent.log"
        systemctl daemon-reload
        systemctl restart openvswitch.service neutron-openvswitch-agent.service
