---
- hosts: all
  tasks:
    - name: create DB
      shell: |
        MYSQL_ROOT_PASSWORD={{ password }}
        SECURE_MYSQL=$(expect -c "
        set timeout 10
        spawn mysql 
        expect \">\"
        send \"CREATE DATABASE nova_api;\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'localhost' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON nova_api.* TO 'nova'@'%' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        send \"CREATE DATABASE nova;\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'localhost' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        send \"GRANT ALL PRIVILEGES ON nova.* TO 'nova'@'%' IDENTIFIED BY  '{{ password }}';\r\"
        expect \">\"
        send \"exit\r\"
        ")
        echo "$SECURE_MYSQL"
    - name: creating Nova environoment
      shell: |
        source ~/openrc.sh
        openstack user create --domain default nova --password {{ password }} --email nova@nico.com
        openstack role add --project admin --user nova admin
        openstack service create --name nova --description "Openstack Compute service" compute
        openstack endpoint create --region RegionOne compute public http://{{ myname }}:8774/v2/%\(tenant_id\)s 
        openstack endpoint create --region RegionOne compute internal http://{{ myname }}:8774/v2/%\(tenant_id\)s 
        openstack endpoint create --region RegionOne compute admin http://{{ myname }}:8774/v2/%\(tenant_id\)s
    - name: install nova and services
      yum: state=present name={{ item }}
      with_items:
      - openstack-nova-api 
      - openstack-nova-conductor 
      - openstack-nova-console
      - openstack-nova-novncproxy
      - openstack-nova-scheduler 
      - openstack-nova-compute 
      - sysfsutils
    - name: configure nova services
      shell: |
        openstack-config --set /etc/nova/nova.conf DEFAULT enabled_apis osapi_compute,metadata
        openstack-config --set /etc/nova/nova.conf api_database connection mysql+pymysql://nova:{{ password }}@{{ myname }}/nova_api
        openstack-config --set /etc/nova/nova.conf database connection mysql+pymysql://nova:{{ password }}@{{ myname }}/nova
        openstack-config --set /etc/nova/nova.conf DEAULT transport_url rabbit://openstack:{{ password }}@{{ myname }}
        openstack-config --set /etc/nova/nova.conf DEFAULT auth_strategy keystone
        openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_uri http://{{ myname }}:5000
        openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_url http://{{ myname }}:35357
        openstack-config --set /etc/nova/nova.conf keystone_authtoken memcached_servers {{ myname }}:11211
        openstack-config --set /etc/nova/nova.conf keystone_authtoken auth_type password
        openstack-config --set /etc/nova/nova.conf keystone_authtoken project_domain_name default
        openstack-config --set /etc/nova/nova.conf keystone_authtoken user_domain_name default
        openstack-config --set /etc/nova/nova.conf keystone_authtoken project_name admin
        openstack-config --set /etc/nova/nova.conf keystone_authtoken username nova
        openstack-config --set /etc/nova/nova.conf keystone_authtoken password {{ password }}
        openstack-config --set /etc/nova/nova.conf DEFAULT my_ip {{ myip }}
        openstack-config --set /etc/nova/nova.conf DEFAULT use_neutron True
        openstack-config --set /etc/nova/nova.conf DEFAULT firewall_driver nova.virt.firewall.NoopFirewallDriver
        openstack-config --set /etc/nova/nova.conf VNC vncserver_listen $my_ip
        openstack-config --set /etc/nova/nova.conf VNC vncserver_proxyclient_address $my_ip
        openstack-config --set /etc/nova/nova.conf libvirt virt_type=qemu
        openstack-config --set /etc/nova/nova.conf libvirt cpu_mode=none
        openstack-config --set /etc/nova/nova.conf glance api_servers http://{{ myname }}:9292
        openstack-config --set /etc/nova/nova.conf oslo_concurrency lock_path /var/lib/nova/tmp
        su -s /bin/sh -c "nova-manage api_db sync" nova
        su -s /bin/sh -c "nova-manage db sync" nova
        systemctl enable openstack-nova-api.service openstack-nova-consoleauth.service openstack-nova-scheduler.service openstack-nova-conductor.service openstack-nova-novncproxy.service
        systemctl start openstack-nova-api.service openstack-nova-consoleauth.service openstack-nova-scheduler.service openstack-nova-conductor.service openstack-nova-novncproxy.service
        systemctl enable libvirtd.service openstack-nova-compute.service
        systemctl start libvirtd.service openstack-nova-compute.service
